name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nodejs-apppp
  DOCKERHUB_USERNAME: pintaramm
  HELM_RELEASE: nodejs-appp
  HELM_CHART_PATH: helm-chart

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      - name: Helm Deploy
        run: |
          helm upgrade --install $HELM_RELEASE $HELM_CHART_PATH \
            --namespace default \
            --create-namespace \
            --set image.repository=$DOCKERHUB_USERNAME/$IMAGE_NAME \
            --set image.tag=latest
